### ISSUE TITLE
Hardcoded frequency in `PytorchForecastingTransform`

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna-ts#106]
### 🐛 Bug Report

How we have this line in `PytorchForecastingTransform.fit`:
```python
ts = TSDataset(df, "1d")
```
The problem is that this `df` can have any frequency.

### Expected behavior

Frequency is calculated instead of hardcoding using `pd.infer_freq`.

### How To Reproduce

Use not daily dataset with neural models.

### Checklist

- [X] Bug appears at the latest library version
- [X] Bug description added
- [X] Steps to reproduce added
- [X] Expected behavior added

**Comment by martins0n** [comment]
Method transform has the same issue аdditionaly.
