### ISSUE TITLE
Add StackingEnsemble class

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna-ts#120]
### 🚀 Feature Request

StackingEnsemble is a class that combines results from several Pipelines.
It uses meta model for combination.

The logic of this Ensemble follows https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.StackingRegressor.html#sklearn.ensemble.StackingRegressor

### Motivation

Make Ensembles in etna-ts even more useful

### Proposal

Because we need to train our meta model we ought to use backtest.
The algorithm is assumed to be as follows:
1. Initialise StackingEnsemble using model as final model, and cv. The cv could be None, Number. CV could be 2 and higher. By default cv=3. 
2. During fit all pipelines are run through backtest to get predictions.
3. Then final model is trained on the predictions
4. Finally pipelines are trained on whole dataset
5. During forecast pipelines return predictions and then its runs through final_model
```
se = StackingEnsemble([Pipeline1, Pipeline2], horizon = 7, final_model=Model, cv=None)
se.fit(data)
se.forecast()
```

In case where Pipeline1 and Pipeline2 have different horizon parameter, StackingEnsemble should return error saying that horizons should be equal.

### Checklist

- [X] Added feature request
- [X] Added motivation
- [X] Added proposal

**Comment by martins0n** [comment]
We've already have features in our forecasts. And we shoud use them for our metamodel. Some features definitely should boost total score (segment class or daytime feature, for example)
ToBe:
```
se = StackingEnsemble([Pipeline1, Pipeline2], final_model=Model, cv=None, features_to_use: Union[None, Literal[all], List[str] = None)
```
If `all` have been chosen we fit model on targets + feature union.

**Comment by julia-shenshina** [comment]
is blocked by #121
