### ISSUE TITLE
Make backtest work with pipeline

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna-ts#121]
### 🚀 Feature Request

Backtest should work with pipeline not bare model. It makes backtest easier as a class.

### Motivation

Backtest implements logic that are now a part of Pipeline class.

### Proposal

--

### Checklist

- [X] Added feature request
- [X] Added motivation
- [x] Added proposal

**Comment by martins0n** [comment]
Proposal:
We shoud just add `backtest` method to `BasePipeline`.
ToBe:
```python
class BasePipeline:
    def __init__(self, horizon, *args, **kwargs):
          pass
    def fit(self, ts):
          pass
    def forecast(self):
          pass
    def backtest(self, ts: TSDataset, metrics: List[Metric], n_folds: int = 5, mode: str = "expand", n_jobs: int = 1):
          pass
```
In the next series we should remove `TimeSeriesCrossvalidation`
