### ISSUE TITLE
Add `hist_outliers` to outliers notebook

### ISSUE THREAD

**Issue by WinstonDovlatov** [tinkoff-ai/etna-ts#198]
### 🚀 Feature Request

Add examples of [hist](https://github.com/tinkoff-ai/etna-ts/blob/master/etna/analysis/outliers/hist_outliers.py) outliers to [outliers notebook](https://github.com/tinkoff-ai/etna-ts/blob/master/examples/outliers.ipynb)

### Motivation

Guide for user on the use of all methods of searching for anomalies

### Proposal

Add examples of [hist](https://github.com/tinkoff-ai/etna-ts/blob/master/etna/analysis/outliers/hist_outliers.py) outliers to [outliers notebook](https://github.com/tinkoff-ai/etna-ts/blob/master/examples/outliers.ipynb)

### Checklist

- [X] Added feature request
- [X] Added motivation
- [X] Added proposal

**Comment by iKintosh** [comment]
Make notebook runs AFTER merge to master
