### ISSUE TITLE
Make `confidence_interval`  work with any column

### ISSUE THREAD

**Issue by WinstonDovlatov** [tinkoff-ai/etna-ts#201]
### 🚀 Feature Request

Make `confidence_interval`  work with any column, not just target

### Motivation

Transforms and methods for detecting anomalies must work with any column

### Proposal

- Make [confidence_interval_outliers](https://github.com/tinkoff-ai/etna-ts/blob/master/etna/analysis/outliers/confidence_interval_outliers.py) work with any column
- Make [ConfidenceIntervalOutliersTransform](https://github.com/tinkoff-ai/etna-ts/blob/master/etna/transforms/outliers.py#L273) work with any column
- Add tests

### Alternatives

Make TSDataset process any column as y_true, not just the target

### Checklist

- [X] Added feature request
- [X] Added motivation
- [X] Added proposal

**Comment by iKintosh** [comment]
Let's create new TSDataset inside transform
