### ISSUE TITLE
Exception in backtest with `aggregate_metrics=True` when using `WandbLogger`

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna-ts#216]
### 🐛 Bug Report

Program fails when backtest with `aggregate_metrics=True` is used inside `WandbLogger` (if given). With `aggregate_metrics=False` everything is fine.

Exception happens in `tslogger.log_backtest_metrics` while constructing `metrics_df`: it can't make `metrics_df.groupby("segment")`. 

Exception was caught in `Pipeline.backtest`, but it looks like this bug also appears in `TimeSeriesCrossValidation` class.

### Expected behavior

No error.

### How To Reproduce

Run backtest with WandLogger while setting `aggregate_metrics=True`. 

### Checklist

- [X] Bug appears at the latest library version
- [X] Bug description added
- [X] Steps to reproduce added
- [X] Expected behavior added

**Comment by Mr-Geekman** [comment]
The key to solve the bug can be [here](https://github.com/tinkoff-ai/etna-ts/blob/d99573326eb9acc3b4dd3148b9e63d2144acc917/etna/loggers/wandb_logger.py#L149)

**Comment by julia-shenshina** [comment]
lets discuss it

**Comment by julia-shenshina** [comment]
check that `fold_number` in df.column before drop
https://github.com/tinkoff-ai/etna-ts/blob/master/etna/loggers/wandb_logger.py#L175
