### ISSUE TITLE
Add `MeanSegmentEncoderTransform`

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna-ts#233]
### 🚀 Feature Request

Add class `MeanSegmentEncoderTransform` that makes mean encoding of the segment.
It should make regressor with name `regressor_segment_mean`, that contains expanding mean of mean target across the segment.

### Motivation

This class can make predictions better.

### Proposal

Add class `MeanSegmentEncoderTransform` that makes mean encoding of the segment.
It should make regressor with name `regressor_segment_mean`, that contains expanding mean of mean target across the segment.

What is expanding mean encoding. It is encoding of the categorical variable based on mean value of the target. At each timestamp we calculate mean value among all previous timestamps -- it can save us from target leakage. For the test data mean on all train data is used.

This technique with some adjustments is used in CatBoost to work with categorical variables. You can read about it [here](https://towardsdatascience.com/how-catboost-encodes-categorical-variables-3866fb2ae640).

The main difficulty in realization of this task is to understand how to make this distinction between train and test data. For example, remembering timestamps on fit stage can be used.

Unfortunately, we can't add multiple permutations, as it violates the temporal structure. However, we can add quantization and prior like in CatBoost in the future if this method proves it successful.

### Test cases

1. Test that we have expanding mean on train, but overall mean on test.
2. Check that this encoding gives a big advantage to `LinearMultiSegmentModel`, that has only this feature. Try to predict something simple like almost constant segments.

**Comment by julia-shenshina** [comment]
Look at

- MeanStatisticsFeature (train part)

- BinsegTrandTransform (future part)
