### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna-ts#65]
### 🚀 Feature Request

etna-ts should have CLI interface

### Motivation

It will make integration of etna-ts in production easier 

### Proposal

etna should be able to run prediction from CLI.
Parameters may be stored in json/yml files.
Input and outputs are csv files.

### Alternatives

https://github.com/fursovia/allenai-common
https://github.com/catalyst-team/hydra-slayer
https://github.com/facebookresearch/hydra

### Checklist

- [X] Added feature request
- [X] Added motivation
- [X] Added proposal

**Comment by julia-shenshina** [comment]
@martins0n can we close this issue?
